// This file is auto-generated by @hey-api/openapi-ts

export type AuthErrorResponse = {
    message?: string | null;
};

export type AuthSuccessResponse = {
    token?: string | null;
    userId?: number;
    username?: string | null;
};

export type CurrentUserResponse = {
    user?: UserDto;
};

export type LoginRequest = {
    username?: string | null;
    password?: string | null;
};

export type RandomPokemonDto = {
    name?: string | null;
    type?: string | null;
    image?: string | null;
};

export type RegisterRequest = {
    username?: string | null;
    email?: string | null;
    password?: string | null;
};

export type UserDto = {
    id?: number;
    username?: string | null;
    email?: string | null;
};

export type PostAuthRegisterData = {
    body?: RegisterRequest;
    path?: never;
    query?: never;
    url: '/Auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Bad Request
     */
    400: AuthErrorResponse;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * OK
     */
    200: AuthSuccessResponse;
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type PostAuthLoginData = {
    body?: LoginRequest;
    path?: never;
    query?: never;
    url: '/Auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Bad Request
     */
    400: AuthErrorResponse;
    /**
     * Unauthorized
     */
    401: AuthErrorResponse;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * OK
     */
    200: AuthSuccessResponse;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/Auth/me';
};

export type GetAuthMeErrors = {
    /**
     * Unauthorized
     */
    401: AuthErrorResponse;
};

export type GetAuthMeError = GetAuthMeErrors[keyof GetAuthMeErrors];

export type GetAuthMeResponses = {
    /**
     * OK
     */
    200: CurrentUserResponse;
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type GetRandomPokemonData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/RandomPokemon';
};

export type GetRandomPokemonResponses = {
    /**
     * OK
     */
    200: RandomPokemonDto;
};

export type GetRandomPokemonResponse = GetRandomPokemonResponses[keyof GetRandomPokemonResponses];

export type GetTestAuthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/TestAuth';
};

export type GetTestAuthResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://localhost:5000' | (string & {});
};
