// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zAuthErrorResponse = z.object({
    message: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zAuthSuccessResponse = z.object({
    token: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    userId: z.optional(z.int()),
    username: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zUserDto = z.object({
    id: z.optional(z.int()),
    username: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    email: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zCurrentUserResponse = z.object({
    user: z.optional(zUserDto)
});

export const zLoginRequest = z.object({
    username: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    password: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zRandomPokemonDto = z.object({
    name: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    type: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    image: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zRegisterRequest = z.object({
    username: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    email: z.optional(z.union([
        z.string(),
        z.null()
    ])),
    password: z.optional(z.union([
        z.string(),
        z.null()
    ]))
});

export const zPostAuthRegisterData = z.object({
    body: z.optional(zRegisterRequest),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostAuthRegisterResponse = zAuthSuccessResponse;

export const zPostAuthLoginData = z.object({
    body: z.optional(zLoginRequest),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zPostAuthLoginResponse = zAuthSuccessResponse;

export const zGetAuthMeData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetAuthMeResponse = zCurrentUserResponse;

export const zGetRandomPokemonData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

/**
 * OK
 */
export const zGetRandomPokemonResponse = zRandomPokemonDto;

export const zGetTestAuthData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});
